name: gostep_app
description: "A simple step counter app built with Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pedometer: ^4.1.1
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4

  # Isar 
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^3.1.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon1.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon1.png"
  min_sdk_android: 21
